import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">nextjs-rust!</a>
        </h1>

        <p className={styles.description}>
          This is a live example of using Next.js and Rust together, served on Shuttle.
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Next.js &rarr;</h2>
            <p>Find in-depth information about Next.js which we're using for the front end.</p>
          </a>

          <a href="https://doc.rust-lang.org/book/" className={styles.card}>
            <h2>Rust &rarr;</h2>
            <p>Learn the basics of Rust, which we're using for the back end.</p>
          </a>

          <a
            href="https://docs.shuttle.rs/introduction/welcome"
            className={styles.card}
          >
            <h2>Shuttle &rarr;</h2>
            <p>Discover and deploy Rust back-ends easily using Shuttle.</p>
          </a>

          <a
            href="https://github.com/joshua-mo-143/nextjs-rust-example"
            className={styles.card}
          >
            <h2>GitHub &rarr;</h2>
            <p>
              Check out this project's GitHub project and view the code.
            </p>
          </a>
        </div>
      </main>
    </div>
  )
}
