[package]
name = "shuttle-next"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
shuttle-axum = "0.24.0"
shuttle-runtime = "0.24.0"
shuttle-static-folder = "0.24.0"
tokio = "1.32.0"
tower-http = { version = "0.4.3", features = ["fs"] }
